### ISSUE TITLE
Error while building the configuration: parsing failure

### ISSUE THREAD

**Issue by lmburns** [Shadow53/hoard#20] opened 2021-06-04 23:52 UTC
System:
```sh
Darwin void.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64 i386 MacBookPro14,1 Darwin
```

I have gotten this error on a couple of the `hoards` I have set:

```sh
 $ hoard -l trace validate                                                           【28s  ~/.conf/hoard  job】─╯
[2021-06-04T23:45:24Z INFO  hoard::config] Loading configuration...
[2021-06-04T23:45:24Z ERROR hoard] error while building the configuration: failed to parse configuration file: data did not match any variant of untagged enum Hoard for key `hoards.gituip` at line 195 column 5
```

This was one of the sections it got hungup on:
```sh
[hoards.gitui]
    [hoards.gitui.conf]
        "macos" = "/Users/lucasburns/.config/gitui/key_config.ron"
    [hoards.gituip.theme]
        "macos" = "/Users/lucasburns/.config/gitui/theme.ron"
```

It also got hungup on another one where the `hoard` was titled `[hoard.bat]` with several sections underneath. On this one (`bat`) I changed the name to `batp` on the parent `hoard` and  changed the name on all of the children `hoards` and it worked.

On the `gitui` one, I tried the same thing but still got the same error. I took out the parent and left only one child, still got the error. Then i changed the name to something random like `asdfasd` and it worked. I then changed it back to `[hoard.gitui]` and then changed all the children back to `gitui` and it works now. There was nothing else that I changed.

### Steps to reproduce:
Error is thrown here:
```sh
[hoards.lazygit]
    [hoards.lazygit.config]
        "macos" = "/Users/lucasburns/.config/lazygit/config.yml"
    [hoards.lazygit.state]
        "macos" = "/Users/lucasburns/.config/lazygit/state.yml"
```
Change to this and still get error:
```sh
[hoards.lazygit.config]
    "macos" = "/Users/lucasburns/.config/lazygit/config.yml"
```
Change to this and no error:
```sh
[hoards.lgasdf]
    "macos" = "/Users/lucasburns/.config/lazygit/config.yml"
```
Add on test to make sure I can use `.`, still no error here:
```sh
[hoards.lgasdf.test]
    "macos" = "/Users/lucasburns/.config/lazygit/config.yml"
```
Change back to lazygit and it still works:
```sh
[hoards.lazygit.test]
    "macos" = "/Users/lucasburns/.config/lazygit/config.yml"
```

**Comment by Shadow53** [comment] 2021-06-05 00:28
Nothing immediately stands out as problematic. Can you share a minimal configuration file that recreates this issue? You can test it without overwriting your current config with the `--config-file` flag.

**Comment by lmburns** [comment] 2021-06-05 00:56
```sh
[envs]
[envs.bat]
    exe_exists = ["bat"]

[envs.macos]
    os = ["macos"]

[hoards]
[hoards.bat]
    [hoards.bat.conf]
        "macos|bat" = "/Users/lucasburns/.config/bat/config"
    [hoards.bat.themes]
        "macos|bat" = "/Users/lucasburns/.config/bat/themes"
    [hoards.bat.syntax]
        "macos|bat" = "/Users/lucasburns/.config/bat/syntaxes"
```

This would've been all that is needed to reproduce the error I encountered earlier. As I had mentioned in the bottom section of that comment where I put steps to reproduce, I fixed the error by following those steps -- renaming the hoard a couple of times. I just tried it with the configuration that I have above, however the error doesn't come up.

I encountered the error 4 times while setting up `hoard`. My whole configuration can be found [here](https://github.com/lmburns/dotfiles/blob/master/.config/hoard/config). I fixed the errors when using this config just by renaming the error a couple of times. 

The 4 errors were names including `[hoards.bat]`, `[hoards.git]`, `[hoards.lazygit]`, and `[hoards.pet]`. I'm not sure if they have any significance, but that's them. I'll report back if I come across any other errors. But these don't seem to be reproducible as of yet after renaming them in my configuration.

**Comment by Shadow53** [comment] 2021-06-05 04:36
Odd that this happened. None of those names should cause any issues. The only one that is at all reserved is "config" (really should document that somewhere).

I'm marking this as "can't reproduce." If anyone comes across this issue in the future and can provide a configuration that reproduces the issue, this can be reopened.

**Closed by Shadow53** 2021-06-05 04:36 UTC
Labels: can't reproduce

**Comment by lmburns** [comment] 2021-06-05 22:15
So `config` is reserved anywhere in the `hoard` name? Or just solely `config`? As in, could I use `[hoards.bat.config]`?

**Comment by Shadow53** [comment] 2021-06-06 23:31
It's actually `[hoard.hoard_name.config]` and `[hoard.hoard_name.pile_name.config]` that are reserved. If you try to use either one, it should give an error message, though not that good of one (yet).

**Comment by Shadow53** [comment] 2021-06-06 23:33
For consistency I may end up also making `[hoards.config]` reserved. Right now, a hoard-level config is the fallback when it exists and a pile-level config does not. So a "global" hoards config may make sense, but either way is not implemented yet.
